"""Generate the in-app brand mark from the launcher icon vector.

The lock screen, the setup flow and the About page all show the app's mark. They used to
show a Material Symbols piggy bank, which had nothing to do with the launcher icon. This
converts res/drawable/ic_launcher_foreground.xml into an inline SVG module so the mark in
the app is the same drawing as the icon on the home screen.

    python tools/generate-brand-mark.py

Re-run it after any change to the launcher foreground.
"""

import importlib.util
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.normpath(os.path.join(HERE, "..", "app", "src", "main", "res"))
OUT = os.path.normpath(os.path.join(
    HERE, "..", "app", "src", "main", "assets", "www", "js", "brand-mark.js"))

# Reuse the vector to SVG conversion rather than writing a second one.
spec = importlib.util.spec_from_file_location(
    "icons", os.path.join(HERE, "generate-legacy-launcher-icons.py"))
icons = importlib.util.module_from_spec(spec)
spec.loader.exec_module(icons)


def main():
    svg = icons.vector_to_svg_paths(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"))

    # The launcher art is white on the brand gradient. In the app the mark sits on whatever
    # surface it is placed on, so the foliage follows the text colour and the coin rims are
    # punched out in the background colour behind them.
    svg = svg.replace('"#FFFFFF"', '"currentColor"').replace('"#0E6B5A"', '"var(--mark-hole)"')
    body = "\n".join(f"    {line}" for line in svg.splitlines())

    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(f'''/*
 * Generated by tools/generate-brand-mark.py. Do not edit by hand.
 *
 * The same drawing as the launcher icon, as an inline SVG. Foliage and trunk follow
 * currentColor; the coin rims use --mark-hole, which each context sets to whatever sits
 * behind the mark.
 */

export function brandMark(className = '') {{
  return `<svg class="brand-mark ${{className}}" viewBox="0 0 108 108" role="img"
       aria-label="Vitta Vriksha" xmlns="http://www.w3.org/2000/svg">
{body}
  </svg>`;
}}
''')

    print(f"wrote {os.path.relpath(OUT, os.path.join(HERE, '..'))}")


if __name__ == "__main__":
    main()
